---
title: "LucyLipoRatio"
author: "Lucy Grigoroff"
date: "2024-03-12"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load packages
```{r}
library(tidyr)
library(tidyverse)
```


# Load Data
```{r}
bus_sau2 <- read.csv("~/git/mahideel/lipoRatio/BusT1_Sau_Healthy_DM2_28112023.csv")
names(bus_sau2)
```

#Data Prep
```{r}
abe <- bus_sau2
abe$L1CE <- abe$L1CH - abe$L1FC
abe$L2CE <- abe$L2CH - abe$L2FC
abe$L3CE <- abe$L3CH - abe$L3FC
abe$L4CE <- abe$L4CH - abe$L4FC
abe$L5CE <- abe$L5CH - abe$L5FC
```



#Mauritius loading data
```{r}
lipoMeta2 <- read.csv("temp_mauritius_annotation.csv", header = TRUE)
load("covid19_mauritius_SER_COVr22_LIPO.daE")
lipoData <- covid19_mauritius_SER_COVr22_LIPO@.Data
# retrieving the sample annotation
lipoMeta<-covid19_mauritius_SER_COVr22_LIPO@obsDescr[[1]] 

# creating sourceID column to match with Survey.No column from anno (metadata)
lipoMeta$sourceID<-as.numeric(sapply(strsplit(lipoMeta$UUID,"_"),"[",2))

# remove LTR
idx<-which(lipoMeta$sampleType %in% c("sample")) # 254 samples - meaning 18 LTR will be taken out
lipoData<-lipoData[idx,]
lipoMeta<-lipoMeta[idx,]

#match 
idx<-which(lipoMeta2$Survey.No %in% lipoMeta$sourceID) #253
lipoMeta2<-lipoMeta2[which(lipoMeta2$Survey.No%in% lipoMeta$sourceID),]
idx<-which(lipoMeta$sourceID %in% lipoMeta2$Survey.No) #253
lipoMeta<-lipoMeta[idx,]
lipoData<-lipoData[idx,]
lipoMeta2<-lipoMeta2[match(lipoMeta$sourceID, lipoMeta2$Survey.No),] #253

#Survey.No == 17 needs the DM status changed to NDM. 
lipoMeta2$DM[which(lipoMeta2$Survey.No=="17")] ="NDM"
```

#make it align with the conventions for saudi and busso cohorts
```{r}
columns_to_keep <- c( "cohortName", "sampleID")
columns_to_keep2 <- c("DM", "Gender", "Age", "Systolic1", "Diastolic1", "BMI", "Height1","Waist1", "Weight1", "FBG")

lipoMeta <- cbind(lipoMeta[, columns_to_keep], lipoMeta2[, columns_to_keep2])
#rm(lipoMeta2)

#gender
lipoMeta$Gender[which(lipoMeta$Gender == "Male")] = "M"
lipoMeta$Gender[which(lipoMeta$Gender == "Female")] = "F"

#new bmi
lipoMeta$BMI_cut <- NA
lipoMeta$BMI_cut[which(lipoMeta$BMI<18.49)] = "Underweight"
lipoMeta$BMI_cut[which(lipoMeta$BMI >= 18.49 & lipoMeta$BMI < 25)] = "Healthy"
lipoMeta$BMI_cut[which(lipoMeta$BMI >= 25 & lipoMeta$BMI < 30)] = "Overweight"
lipoMeta$BMI_cut[which(lipoMeta$BMI >= 30)] = "Obese"

#DM
lipoMeta$DM[lipoMeta$DM == "NDM"] <- "NO DM"
lipoMeta$DM[lipoMeta$DM == "DM"] <- "DM2"

#Creating a new column for comb of BMI category and DM
lipoMeta$comb <- NA
lipoMeta$comb = gsub("\\s","", paste(lipoMeta$BMI_cut,"_", lipoMeta$DM))

# renaming and adding columns of bus_sau to be consistent with Mauritius
names(lipoMeta )[names(lipoMeta ) == "Age"] <- "age"
names(lipoMeta )[names(lipoMeta ) == "BMI"] <- "bmi"
names(lipoMeta )[names(lipoMeta ) == "Gender"] <- "sex"
names(lipoMeta )[names(lipoMeta ) == "BMI_cut"] <- "BMI.weight"
names(lipoMeta )[names(lipoMeta ) == "Systolic1"] <- "sbp"
names(lipoMeta )[names(lipoMeta ) == "Diastolic1"] <- "dbp"
names(lipoMeta )[names(lipoMeta ) == "Height1"] <- "height"
names(lipoMeta )[names(lipoMeta ) == "Weight1"] <- "weight"
names(lipoMeta )[names(lipoMeta ) == "Waist1"] <- "waist"
names(lipoMeta )[names(lipoMeta ) == "cohortName"] <- "cohort"
names(lipoMeta )[names(lipoMeta ) == "FBG"] <- "glucose"

lipoData <- as.data.frame(lipoData)
lipoData$L1CE <- lipoData$L1CH - lipoData$L1FC
lipoData$L2CE <- lipoData$L2CH - lipoData$L2FC
lipoData$L3CE <- lipoData$L3CH - lipoData$L3FC
lipoData$L4CE <- lipoData$L4CH - lipoData$L4FC
lipoData$L5CE <- lipoData$L5CH - lipoData$L5FC

mau <- cbind(lipoData, lipoMeta)

#rm(lipoData, lipoMeta)
```

#add mau to saudi and bus
```{r}
cols_abe <- colnames(abe)
cols_mau <- colnames(mau)

# Reorder the columns of df2 to match the order of columns in df1
mau <- mau[, cols_abe]

abem <- rbind(abe, mau)

```

#Lipo composition per each subfraction (phillip)
based on ratio, particle number explanation
```{r}
# Calculate total lipid for each level
abem$L1TotLip <- rowSums(abem[, c("L1TG", "L1FC", "L1CE", "L1PL")])
abem$L2TotLip <- rowSums(abem[, c("L2TG", "L2FC", "L2CE", "L2PL")])
abem$L3TotLip <- rowSums(abem[, c("L3TG", "L3FC", "L3CE", "L3PL")])
abem$L4TotLip <- rowSums(abem[, c("L4TG", "L4FC", "L4CE", "L4PL")])
abem$L5TotLip <- rowSums(abem[, c("L5TG", "L5FC", "L5CE", "L5PL")])

# Calculate percentages for each lipid component at each level, Do CH not CE as you use CH and FC to make CE
lipids <- c("TG", "FC", "CE", "PL")

for (level in 1:5) {
  for (lipid in lipids) {
    abem[[paste0("L", level, lipid, "%")]] <- abem[[paste0("L", level, lipid)]] / abem[[paste0("L", level, "TotLip")]]
  }
}

```

#Pie Chart Function
```{r}
generate_pie_chart <- function(data, variable, particleNo = T) {
  # Filter the data based on the selected variable
  # use either the particle number or just regular data
  if(particleNo == T){
    vars <- grep(pattern = paste0(variable, ".*[^BNH]%"),
             x = names(data),
             value = TRUE)
  } else {
    #if you don't want to use the % of total
    vars <- grep(pattern = paste0(variable, ".*[^BNH]$"),
             x = names(data)[!grepl("%|TotLip", names(data))],
             value = TRUE)
  }
  
  df <- data[, c("cohort", "comb", vars)]

  # Pivot the data longer
  dF <- pivot_longer(data = df, cols = vars)

  # Summarize the data
  dF <- group_by(dF, cohort, comb, name) %>%
    summarise(avg = mean(value), .groups = "drop")
  
  # Ensure all combinations of 'comb' and 'name' are present with zero values
  df <- tidyr::complete(dF, comb, name, fill = list(avg = 0))

  # Normalize the 'avg' values within each cohort and comb
  df <- df %>%
    group_by(cohort, comb) %>%
    mutate(normalized_avg = avg / sum(avg))

  # Create the pie chart
  pie_chart <- ggplot(df, aes(x = "", y = normalized_avg, fill = name)) +
    geom_bar(stat = "identity", width = 1) +  # Create bars with identity stat and width 1
    coord_polar(theta = "y") +  # Convert to polar coordinates
    scale_fill_manual(values = c("red", "green", "blue", "pink"))+
    #scale_fill_manual(values = scales::hue_pal()(length(unique(dF$name)))) +  # Use the same colors as the bar chart
    theme_void() +  # Remove unnecessary elements
    theme(legend.position = "right", # Position legend theme
          strip.placement = "outside",
          strip.text = element_text(size = 12),
          strip.text.y = element_text(angle = 90),
          axis.text.y = element_text(hjust = 0),
          strip.background = element_rect(fill = "white", 
                                          color = "white"),
           panel.spacing = unit(0, "lines"))+
    facet_grid(facets = cohort ~ comb, switch = "y") +
    geom_text(aes(label = round(avg, digits = 2)), 
              position = position_stack(vjust = 0.5)) +
    labs(fill = NULL)
  
  return(pie_chart)
}


```

```{r}
#only health weight and obese 
unique(abem$BMI.weight)
abem2 <- na.omit( abem[abem$BMI.weight %in% c("Healthy", "Obese"), ])

pie_chart_L1 <- generate_pie_chart(data = abem2, variable = "L1")
pie_chart_L1 + ggtitle("L1")
pie_chart_L2 <- generate_pie_chart(data = abem2, variable = "L2")
pie_chart_L2 + ggtitle("L2")
pie_chart_L3 <- generate_pie_chart(data = abem2, variable = "L3")
pie_chart_L3 + ggtitle("L3")
pie_chart_L4 <- generate_pie_chart(data = abem2, variable = "L4")
pie_chart_L4 + ggtitle("L4")
pie_chart_L5 <- generate_pie_chart(data = abem2, variable = "L5")
pie_chart_L5 + ggtitle("L5")
```

#L2 L5 Ratio
```{r}

# Calculate percentages for each lipid component at each level, Do CE not CH as you use CH and FC to make CE
lipids <- c("TG", "FC", "CE", "PL")

  for (lipid in lipids) {
    abem[[paste0("ratio", lipid, "%")]] <- abem[[paste0("L2", lipid, "%")]] / abem[[paste0("L5", lipid, "%")]]
  }
abem2<- na.omit( abem[abem$BMI.weight %in% c("Healthy", "Obese"), ])

idx <- which(is.infinite(abem2$`ratioTG%`) |is.infinite(abem2$`ratioFC%`) |is.infinite(abem2$`ratioCE%`) |is.infinite(abem2$`ratioPL%`) )
abem2<- abem2[-idx,]

generate_pie_chart(data = abem2, variable = "ratio")
```

#boxplots of healthy (DM and NDM)
```{r}

# Define the columns to be plotted
columns_to_plot <- c( "L2TG%", "L5TG%")

# Create a long format of the data frame
health_long <- tidyr::pivot_longer(abem2, cols = columns_to_plot)

facet_counts <- count(abem2, cohort, DM)
# BoxPlot
ggplot(health_long, aes(x = name, y = value)) +
  geom_boxplot() +
  facet_grid(cohort ~ DM, scales = "free_x", switch = "y") +  # cohort on the side, DM on top
  geom_text(data = facet_counts, aes(label = n, x = Inf, y = Inf), hjust = 1, vjust = 1)+
  labs(x = "Variable", y = "Value") +
  theme_bw() +
  ggtitle("Healthy Weight TG by particle No")

# Distribution Plot
ggplot(health_long, aes(x = value, fill = name)) +
  geom_density(alpha = 0.5) +  # Use geom_density() for distribution plots
  facet_grid(cohort ~ DM, scales = "free_x", switch = "y") +  # cohort on the side, DM on top
  #geom_text(data = facet_counts, aes(label = n, x = Inf, y = Inf), hjust = 1, vjust = 1) +
  labs(x = "Value", y = "Density") +  # Adjust axis labels accordingly
  theme_bw() +
  ggtitle("Healthy Weight TG by particle No")


cohort_dm_table <- table(abem2$cohort, abem2$DM)

# Convert the table to a data frame for better visualization
cohort_dm_df <- as.data.frame.matrix(cohort_dm_table)

# Set meaningful column names
colnames(cohort_dm_df) <- c("NO DM", "DM")

# Print the table
print(cohort_dm_df)

```

#mauritius outliers
```{r}
idx <- which(abem2$BMI.weight == "Healthy" & abem2$DM =="NO DM")

healthNODM <- abem2[idx,]

samp<- healthNODM[which(healthNODM$cohort == "mauritius"), "sampleID"]

matching_sourceIDs <- lipoMeta[lipoMeta$sampleID %in% samp, "sourceID"]

maumeta<-
  read_xls("~/Downloads/Mauritius_cohort_metadataFeb2024 (1).xls")

maumeta <- maumeta[maumeta$Survey.No. %in% matching_sourceIDs, ]


maumeta$Have.you.ever.been.tested.positive.to.COVID.19..
maumeta$Have.you.been.hospitalised.for.COVID.19.
maumeta$High.blood.Cholesterol.Confirmation

```